### ISSUE TITLE
Cannot override css for embedded form

### ISSUE THREAD

**Issue by maderlock** [checkout/checkout-magento2-plugin#12]
Although there is an option to set a custom css file, there is hard-coded css that is always output after this. It is this hard-coded css that we would like to override but lack a mechanism to do so.

See view/frontend/templates/embedded.phtml

Alternatively, you could always make the changes we suggested in #10 ;)

**Comment by david-fiaty-cko** [comment]
Here is the CSS available in the file you mention:
`
    html {
        overflow: -moz-scrollbars-vertical !important; 
        overflow-y: scroll !important;
    }

    #embeddedForm {
        z-index: 0 !important;
    }
    
    #embeddedForm, #embeddedForm iframe {
        position: relative !important;
    }

    #embeddedForm iframe {
        min-height: 153px;
    }

    #cko-form-holder {
        max-width: 50%;
    }
`

I agree that the html selector could be removed. It's not absolutely necessary, even though it covers a few cross browser compatibility issues in specific cases that may not be experienced by most of the users.

Apart from that I don't see what else you would want to override that you can't. Point by point:

- The  #embeddedForm z-index: 0 !important;
This one covers a bug that you reported. Adding it guarantees that you can display whatever you want over the form. You can still use negative z-index for elements you would like to place under the form.

- #embeddedForm, #embeddedForm iframe position: relative !important
This one is the most important. If you remove it, the form will simply disappear. This is by design and there is nothing we can do about it.

- #embeddedForm iframe  min-height: 153px;
This one is by design too. You just can't display the entire Checkout.com Embedded form with a lower value.

Could you please be more specific about what you would like to override that you can't at the moment, and why?

**Comment by maderlock** [comment]
This one:

    #cko-form-holder {
        max-width: 50%;
    }

I suppose can override this by using a more specific selector.

**Comment by david-fiaty-cko** [comment]
Yes you can, either with a more specific selector or a !important.
Please note that once we've added media queries as you suggest, customising the width will require a little bit more effort. However I don't think we will need more than 3 or 4 media queries.

We know we can't take in account width requirements for all user templates, so customisation for this specific selector is to expect. The website you are working on now requires a different width but another website might not need it.

For one single selector, it seems that a custom CSS file is the best option. You can do it by uploading a custom CSS file to the config of the module, or just by adding the selector in a theme CSS file. The priority of selectors won't matter if you use !important.

**Comment by maderlock** [comment]
While I can't say I 100% agree with some of the default choices, I can see how I can customise this, so closing this issue.
