### ISSUE TITLE
How to override CheckoutCom\Magento2\Gateway\Http\TransferFactory

### ISSUE THREAD

**Issue by kaushalsutharoc** [checkout/checkout-magento2-plugin#151]
Not an issue but need suggestion.

I'm trying to override the function `create()` from `CheckoutCom\Magento2\Gateway\Http\TransferFactory` file.

I've added following
`<preference for="CheckoutCom\Magento2\Gateway\Http\TransferFactory" type="Mymodule\CheckoutCom\Gateway\Http\TransferFactory" />`

But it's not working.

I need to override because I want to use the different secret key from different website due to some calculations on the fly.

**Comment by david-fiaty-cko** [comment]
@kaushalsutharoc the module you're currently testing will be deprecated in a few days.
Please try the first release of the 2.0 series available here (upa branch): https://github.com/checkout/checkout-magento2-plugin/tree/upa

You can also get it via composer with the following command:
composer update checkoutcom/magento2:dev-upa

The module has been completely re-written, tested and has many additional features.
The TransferFactory class is not used and all http requests are delegated to our PHP SDK with CURL calls: https://github.com/checkout/checkout-sdk-php

In order to use different keys, you can override the targeted class and modify the SDK calls. Please refer to the SDK's wiki for usage details.

**Comment by kaushalsutharoc** [comment]
Thanks @david-fiaty-cko
