### ISSUE TITLE
Error when changing css

### ISSUE THREAD

**Issue by maderlock** [checkout/checkout-magento2-plugin#29]
Using v2.011 of extension
v2.1.9 of Magento 2

When trying to change css from custom to standard, it will not change and gives me the following error:

Something went wrong while saving this configuration: Notice: Undefined index: tmp_name in .../web-root/vendor/checkoutcom/magento2/Model/Config/Backend/CustomCss.php on line 52

**Comment by maderlock** [comment]
The reason I'd like to change the option is that I get the following error in the console on the page when using a custom css file:

https://www.dropbox.com/s/iu2fnj2s47e76v9/Screenshot%202017-11-14%2015.06.36.png?dl=0

**Comment by maderlock** [comment]
And this:

https://www.dropbox.com/s/fg29p4k8k0jws5o/Screenshot%202017-11-14%2015.07.18.png?dl=0

**Comment by david-fiaty-cko** [comment]
Thank you for reporting this issue, it will be fixed in the next release.

For now, in order to change CSS from custom to standard, you can still click on the "delete" checkbox next to your file, then save the configuration.

This will effectively delete the custom CSS file and bring back the default one.

**Comment by david-fiaty-cko** [comment]
These issues have been fixed in the latest release 1.0.13.
