### ISSUE TITLE
Errors within Configuration -> Payment methods page

### ISSUE THREAD

**Issue by halitsavafoglu** [checkout/checkout-magento2-plugin#329]
I've installed the latest version of your extension 2.2.6 on my Magento 2.2.3 store manually inside the path:
app/code/CheckoutCom/Magento2

Unfortunately, I'm receiving an error when I reach Store -> Configuration -> Payment Methods:
Class Checkout\Library\HttpHandler does not exist

Details in the log/system.log:

main.CRITICAL: Class Checkout\Library\HttpHandler does not exist [] []
main.CRITICAL: Class Checkout\Library\HttpHandler does not exist [] []
main.CRITICAL: Invalid block type: CheckoutCom\Magento2\Block\Adminhtml\System\Config\Fieldset\Payment [] []

**Comment by david-fiaty-cko** [comment]
@khaledsawwaf the Checkout.com M2 module depends on the Checkout.com SDK: https://github.com/checkout/checkout-sdk-php

This SDK is declared as a dependency in the composer.json file and is installed automatically when you run the installation of the Checkout.com M2 module via composer. The error you're having shows that the PHP SDK can't be found on your installation.

Because manual installation is tedious, we do not advertise or document it. The recommended way is to use composer.
Please have a look at the readme file for more info on how to install it: https://github.com/checkout/checkout-magento2-plugin
