### ISSUE TITLE
M2.4.2 - Major Issues with the module

### ISSUE THREAD

**Issue by IbrahimS2** [checkout/checkout-magento2-plugin#482]
- The orders captured from guest users not collecting their emails/names etc.. and only registered against mail@example.com, and 
- Webhooks cannot be traced, how would I know what callbacks failed due to firewall or any other issue?
- All orders with callbacks that failed for any reason gets closed and we end up with payment taken and order closed which is a nightmare for admin users!!!

In conclusion, the module is not working well, with no support whatsoever and I am opening this as an issue for the second time, the first time it got deleted somehow and I hope this makes it through.

**Comment by IbrahimS2** [comment]
@aamant @likemusic HELP!

**Comment by likemusic** [comment]
@IbrahimS2 I don't use this module since my last issues here, so I can't help you now.

**Comment by IbrahimS2** [comment]
@david-fiaty-cko HELP!

**Comment by aamant** [comment]
@IbrahimS2 I don't use this module since my lasst issues here, so I can't help you now.

**Comment by bakshivarun** [comment]
Hi, Ibrahim. Apologies for your issue not being looked into the first time but we are actively looking into them. More updates as I get them.

**Comment by bakshivarun** [comment]
@IbrahimS2 Coming back to your listed issues:

1. We have not been able to replicate this issue because there's no record of mail@example.com. We register Guest emails from the billing address. FYI - Customer Name = _Guest_ is expected behaviour. 

For 2. and 3., could you give us explicit examples and steps to reproduce, please? We're more than happy to look into these issues for you. Would also appreciate what version of our plugin you're using? Thanks again!
