### ISSUE TITLE
Multiple Capture of Payments

### ISSUE THREAD

**Issue by maderlock** [checkout/checkout-magento2-plugin#50]
Setup:
Magento 2.2.3
Checkout.com module 1.0.20
Auto Capture Time: 1 hour
Integration: Frames
Debug: no (now turned on, but too late for this to help right now)

We are seeing a number of instances of orders being charged 2 (or more!) times. Looking at the access logs, the callback action is being called by checkout.com multiple times. Logging into the checkout.com hub I can see multiple authorisations that are then all getting captured. On the Magento side, the orders only show the last authorisation, but all the captures are being logged.

Example order in Magento with one authorisation but multiple captures:
![screenshot 2018-04-10 11b safe](https://user-images.githubusercontent.com/630320/38554321-127ddf78-3cba-11e8-86e8-3f620286ff7d.jpg)

Here are the authorizations and captures from the hub:
![screenshot 2018-04-10 11 safe](https://user-images.githubusercontent.com/630320/38554334-1f16707e-3cba-11e8-9bb8-441b59297251.jpg)

Here is an access log for a similar case that had only two captures:
![screenshot 2018-04-10 12 safe](https://user-images.githubusercontent.com/630320/38554855-0f8ae5fc-3cbc-11e8-98ef-20e2b5829da6.jpg)

You can see that the checkout is only entered once, but there are two calls to payment details, suggesting that they submitted twice.

Any idea how multiple authorizations might be being made? We did not get any reports of errors from the customers, and cannot see anything in the error logs on the server.

**Comment by david-fiaty-cko** [comment]
Checking the orders with duplicated charges show 1 common point: they seem to have been all placed by non logged in users. This leads to a plugin added to the module, in order to overcome a core issue where orders could be lost on the checkout page in Magento 2.1 and below.

The purpose of the plugin was to force the order placement in the case the order was lost for non logged in users, and also improve the error messages in case the order placement still fails.

It appears that the issue has been fixed in Magento 2.2 and above, making the plugin a duplicated place order action.

An update is available in the latest release 1.0.23. 
Please reopen if necessary.

**Comment by david-fiaty** [comment]
Please try the latest version of the module and reopen if necessary.
