### ISSUE TITLE
Custom url for failured payment

### ISSUE THREAD

**Issue by likemusic** [checkout/checkout-magento2-plugin#95]
At the moment (for iframe integration) if user input invalid card data (for example bad cvv) hi is redirected to "checkout/cart". To fix his mistake he should:

1) Click "Proceed to checkout" to go to "checkout/#shipping".
2) Click "Next" to go to "checkout/#payment" and see iframe where to put card data.

In my case I have one more custom step between "checkout/#shipping" and "checkout/#payment".

Threrefore it wold be better for UX redirect user directly to "checkout/#payment" on failed payment. Or to have this url in plugin config. Or separate getter for result url for failed payment to interface method, to have possibilities to overwrite it in custom separated magento module.

**Comment by david-fiaty-cko** [comment]
@likemusic, custom integrations that do not follow the core Magento 2 checkout process can indeed create issues in specific cases. 

Some One Step Checkout modules for example will not work properly with third party payment modules because of the way these modules are designed.

Even though we try to be compatible with a maximum of third party integrations, we can't ensure 100% compatibility with all custom integrations.

The flow currently in place works for most integrations following the core M2 design. Please provide more information about your specific case: 

1- How has this extra step been added to your integration?
2- What is the purpose of the custom step you have added to the checkout process?
3- Are you using a third party module (which one) or have you added a custom development?

**Comment by david-fiaty-cko** [comment]
@likemusic, the #payment page will not display messages broadcasted using the Magento\Framework\Message\ManagerInterface class. We need to display error messages when returning from the gateway, which is the reason why we use the /cart page.

This will be improved in and upcoming release via the use of AJAX for the gateway requests. However redirecting to the #payment page as you asked is not doable as it will prevent important messages from displaying.

**Comment by likemusic** [comment]
@david-fiaty-cko 
> 1 How has this extra step been added to your integration?

By custom module. But for this issue it doesn't matter, how added new steps. 

> 2- What is the purpose of the custom step you have added to the checkout process?

We separate managing billing address to separate step, but it doesn't matter for this issue.

> 3- Are you using a third party module (which one) or have you added a custom development?

We ase use many third party module, but it doesn't matter for this issue.

The point of this bug is just suggest you to redirect after failure payment not to cart  page (`checkout/cart`), but to checkout payment step (`checkout/#shipping`). Because it would be more user-frendly for customers.

I could create pull-request for this change, if you approve it.

I suggest to create plugin-config for this, because it woud be more flexible for magento store admin's.

Also I suggest to create separate getter interface for result url for failed payment because it would be more clean way than create after-method interceptor for [\CheckoutCom\Magento2\Controller\Payment\Fail::execute()](https://github.com/checkout/checkout-magento2-plugin/blob/master/Controller/Payment/Fail.php).

**Comment by likemusic** [comment]
@david-fiaty-cko I don't understand why you close issue before you get feedback on it?
